### ISSUE TITLE
Change commit messages to something usefull

### ISSUE THREAD

**Issue by Ticamus** [Scunl/APP1-PB1#1]
I think "push" isn't a good message to explain what the commit is about and should be changed to something more explicit.

**Comment by Scunl** [comment]
I think u should shut u f up

**Comment by Scunl** [comment]
> I think "push" isn't a good message to explain what the commit is about and should be changed to something more explicit.

I think u should shut u f up mate

**Comment by Ticamus** [comment]
> > I think "push" isn't a good message to explain what the commit is about and should be changed to something more explicit.
> 
> I think u should shut u f up mate

ok so the owner is an asshole
